// <auto-generated />
namespace PAC.DATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ovarhaul2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ovarhaul2));
        
        string IMigrationMetadata.Id
        {
            get { return "202108200058143_ovarhaul2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
